### ISSUE TITLE
[feature] pick last used profile

### ISSUE THREAD

**Issue by tomsquest** [stevenxxiu/albert_firefox#1]
Hi @stevenxxiu ,

#### Goal

▶️ The feature would be to use the last profile used.

#### Details

In the current code, which profile to use is hardcoded:
```python
firefox_data_path / profile.get('Profile0', 'Path')
```

In my current setup, it seems I have 3 profiles (firefox, firefox developer and a mysterious one).

I saw that there is a param `[General] Version=2` which gives the last profile used:

```ini
[General]
StartWithLastProfile=1
Version=2
```

Remarks:
- `StartWithLastProfile` seems to specify *if* the user wants to use the last profile, indicated by `Version`.

#### my profiles.ini

```ini
[Install4F96D1932A9F858E]
Default=9cunpr3o.default-release
Locked=1

[Profile1]
Name=default
IsRelative=1
Path=4rkx4695.default
Default=1

[Install4808706AC02A9B45]
Default=pe0cppkh.dev-edition-default-1717775821373
Locked=1

[Profile0]
Name=dev-edition-default
IsRelative=1
Path=pe0cppkh.dev-edition-default-1717775821373

[General]
StartWithLastProfile=1
Version=2

[Profile2]
Name=default-release
IsRelative=1
Path=9cunpr3o.default-release


```

**Comment by stevenxxiu** [comment]
Well this was trickier than I expected. The docs at [Profile Manager - Create, remove or switch Firefox profiles | Firefox Help](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles) say:

> - `Default=1` refers to the last selected profile.

But this doesn't apply to dev profiles. I could give some config for the user to pick the profile, but I think most people just stick with one profile. I just pick the last used normal profile if it's been used, and if not then the dev profile.

**Comment by tomsquest** [comment]
Excellent, LGTM!
