### ISSUE TITLE
[bug] a bookmark can have no name

### ISSUE THREAD

**Issue by tomsquest** [stevenxxiu/albert_firefox#3]
The plugin crashes given a bookmark has no name.

Why it's possible? I do have bookmarks, in the toolbar, without a name, but just the icon.

The bug is here:
```python
            name_index = name.lower().find(query_str)  # <------ name can be None
            url_index = url.lower().find(query_str)
```

I added a check on name (and url) and everything went fine:

```
        for i, (name, url) in enumerate(self.bookmarks):

            if name is None:
                name = ""
            if url is None:
                url = ""

            name_index = name.lower().find(query_str)
            url_index = url.lower().find(query_str)
```

Maybe the best option if to filter out those bookmarks at the **query** level (when reading from sqlite).

**Comment by stevenxxiu** [comment]
Thanks for the suggestion. I match URLs too, so I just handled empty names in this instance.
